USE [master]
GO

/****** Object:  Database [Employees]    Script Date: 11/04/2026 16:00:16 ******/
CREATE DATABASE [Employees]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Employees', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\Employees.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Employees_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\Employees_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Employees].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Employees] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Employees] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Employees] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Employees] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Employees] SET ARITHABORT OFF 
GO

ALTER DATABASE [Employees] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Employees] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Employees] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Employees] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Employees] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Employees] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Employees] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Employees] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Employees] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Employees] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Employees] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Employees] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Employees] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Employees] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Employees] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Employees] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Employees] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Employees] SET RECOVERY FULL 
GO

ALTER DATABASE [Employees] SET  MULTI_USER 
GO

ALTER DATABASE [Employees] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Employees] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Employees] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Employees] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Employees] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Employees] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [Employees] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Employees] SET QUERY_STORE = ON
GO

ALTER DATABASE [Employees] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Employees] SET  READ_WRITE 
GO

